apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: edge-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: edge-be-sample02
          image: 44ce789b-kr1-registry.container.nhncloud.com/container-platform-registry/edge-be-sample02:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ncr
---

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: edge-test
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31031
  type: NodePort
